apiVersion: v1
kind: ConfigMap
metadata:
  name: retriever-config
  namespace: faultatlas
data:
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  MONGO_DB: "faultatlas"
  OPENAI_EMBEDDING_MODEL: "text-embedding-3-small"
