apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
  namespace: faultatlas
  labels:
    app: ingestion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: faultatlas/ingestion:latest
          envFrom:
            - configMapRef:
                name: ingestion-config
            - secretRef:
                name: faultatlas-secrets
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "1Gi"
