apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faultatlas-ingress
  namespace: faultatlas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: faultatlas.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-svc
                port:
                  number: 8000
